Repository googleapis/nodejs-binary-authorization, pull requests merged in 2021-02, with the labels that each got.

#10 chore: update CODEOWNERS config
  .github/CODEOWNERS
Labels: automerge, cla: yes

#9 build: migrate to flakybot
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline_v2.sh
Labels: automerge, cla: yes

#15 build: fix package name
  .jsdoc.js
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline_v2.sh
  linkinator.config.json
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  src/v1beta1/binauthz_management_service_v1_beta1_client.ts
  src/v1beta1/gapic_metadata.json
  src/v1beta1/index.ts
  synth.metadata
  system-test/fixtures/sample/src/index.js
  system-test/fixtures/sample/src/index.ts
  system-test/install.ts
  test/gapic_binauthz_management_service_v1_beta1_v1beta1.ts
Labels: cla: yes, context: partial

#17 docs: update docs
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline_v2.sh
  CONTRIBUTING.md
  README.md
  synth.metadata
Labels: cla: yes, context: full

#18 docs: Replace "whitelist" with "allowlist" in generated documentation
  protos/google/cloud/binaryauthorization/v1beta1/resources.proto
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  synth.metadata
Labels: cla: yes, context: full
