Repository googleapis/nodejs-binary-authorization, pull requests merged in 2021-03, with the labels that each got.

#20 build: update gapic-generator-typescript to v1.2.10.
  synth.metadata
  webpack.config.js
Labels: api: binaryauthorization, automerge, cla: yes, context: full

#19 fix(docs): downgrade to beta to match release level
  .repo-metadata.json
  README.md
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  synth.metadata
Labels: api: binaryauthorization, automerge, cla: yes

#22 build: adds style enum
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  synth.metadata
Labels: api: binaryauthorization, cla: yes, context: none

#23 chore: migrate to owl bot
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  .repo-metadata.json
  synth.metadata
  synth.py
Labels: api: binaryauthorization, cla: yes
